/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 UCCLowerLevel.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/UCCLowerLevel.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Exterior_Walls.geometry} material={materials.Wall_material} position={[-2.16, 0, -5.04]}>
        <mesh geometry={nodes.Floor031.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Western_Chiropractic_49.geometry} material={materials.Wall_material} position={[0.35, 0, 0.42]}>
        <mesh geometry={nodes.Floor024.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.UCC_Dental.geometry} material={materials.Wall_material} position={[1.5, 0, -1.81]}>
        <mesh geometry={nodes.Floor009.geometry} material={nodes.Floor009.material} />
      </mesh>
      <mesh geometry={nodes.Starbucks.geometry} material={materials.Wall_material} position={[2.23, 0, -2.86]}>
        <mesh geometry={nodes.Floor007.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Smooth_Wax_Bar_80.geometry} material={materials.Wall_material} position={[-1.61, 0, -1.53]}>
        <mesh geometry={nodes.Floor020.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes['Rooms_11-32'].geometry} material={materials.Wall_material} position={[-2.36, 0, -3.74]}>
        <mesh geometry={nodes.Floor.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Lifetouch_Photography_79.geometry} material={materials.Wall_material} position={[-0.68, 0, -0.51]}>
        <mesh geometry={nodes.Floor023.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_78.geometry} material={materials.Wall_material} position={[-0.68, 0, -0.84]}>
        <mesh geometry={nodes.Floor022.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_76A.geometry} material={materials.Wall_material} position={[-1.22, 0, -1.53]}>
        <mesh geometry={nodes.Floor017.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_75.geometry} material={materials.Wall_material} position={[-0.2, 0, -0.93]}>
        <mesh geometry={nodes.Floor013.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Grocery_Store_73.geometry} material={materials.Wall_material} position={[-0.42, 0, -0.12]}>
        <mesh geometry={nodes.Floor021.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_67.geometry} material={materials.Wall_material} position={[-0.56, 0, 0.95]}>
        <mesh geometry={nodes.Floor044.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_66.geometry} material={materials.Wall_material} position={[-1.57, 0, 1.18]}>
        <mesh geometry={nodes.Floor027.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_65.geometry} material={materials.Wall_material} position={[-0.57, 0, 1.43]}>
        <mesh geometry={nodes.Floor045.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_63.geometry} material={materials.Wall_material} position={[-0.56, 0, 1.9]}>
        <mesh geometry={nodes.Floor036.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_61.geometry} material={materials.Wall_material} position={[-0.9, 0, 3.04]}>
        <mesh geometry={nodes.Floor039.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_60.geometry} material={materials.Wall_material} position={[-0.9, 0, 2.5]}>
        <mesh geometry={nodes.Floor040.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_59.geometry} material={materials.Wall_material} position={[-0.35, 0, 2.51]}>
        <mesh geometry={nodes.Floor041.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_58.geometry} material={materials.Wall_material} position={[-0.35, 0, 3.05]}>
        <mesh geometry={nodes.Floor038.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_57.geometry} material={materials.Wall_material} position={[0.52, 0, 2.66]}>
        <mesh geometry={nodes.Floor043.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_56.geometry} material={materials.Wall_material} position={[1.91, 0, 2.65]}>
        <mesh geometry={nodes.Floor015.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_54B.geometry} material={materials.Wall_material} position={[1.63, 0, 1.79]}>
        <mesh geometry={nodes.Floor032.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_54A.geometry} material={materials.Wall_material} position={[1.04, 0, 1.79]}>
        <mesh geometry={nodes.Floor033.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_53.geometry} material={materials.Wall_material} position={[0.44, 0, 1.78]}>
        <mesh geometry={nodes.Floor034.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_47.geometry} material={materials.Wall_material} position={[0.69, 0, 0.41]}>
        <mesh geometry={nodes.Floor025.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_41.geometry} material={materials.Wall_material} position={[1.27, 0, 0.41]}>
        <mesh geometry={nodes.Floor026.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_37.geometry} material={materials.Wall_material} position={[1.67, 0, 0.26]} rotation={[0, 0, -Math.PI]} scale={-1}>
        <mesh geometry={nodes.Floor012.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_36B.geometry} material={materials.Wall_material} position={[0.47, 0, -1.34]}>
        <mesh geometry={nodes.Floor006.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_36A.geometry} material={materials.Wall_material} position={[1.14, 0, -1.25]}>
        <mesh geometry={nodes.Floor010.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_34B.geometry} material={materials.Wall_material} position={[2.24, 0, -3.23]}>
        <mesh geometry={nodes.Floor004.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Life_Labs_34A.geometry} material={materials.Wall_material} position={[2.25, 0, -3.7]}>
        <mesh geometry={nodes.Floor003.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Pharmacy.geometry} material={materials.Wall_material} position={[0.2, 0, -0.96]}>
        <mesh geometry={nodes.Floor011.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Peersupport_76.geometry} material={materials.Wall_material} position={[-0.68, 0, -1.53]}>
        <mesh geometry={nodes.Floor005.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Multifaith_38.geometry} material={materials.Wall_material} position={[2.02, 0, -0.57]}>
        <mesh geometry={nodes.Floor029.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Food_Support_Services_40.geometry} material={materials.Wall_material} position={[2, 0, 1.19]} rotation={[0, 0, -Math.PI]} scale={-1}>
        <mesh geometry={nodes.Floor030.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Campus_Vision_36C.geometry} material={materials.Wall_material} position={[0.48, 0.02, -1.35]}>
        <mesh geometry={nodes.Floor008.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Bookstore_Western.geometry} material={materials.Wall_material} position={[-1.72, 0, -3.62]}>
        <mesh geometry={nodes.Floor001.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Bathroom_1.geometry} material={materials.Wall_material} position={[-1.89, 0, -3.53]}>
        <mesh geometry={nodes.Floor002.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Bathroom_2.geometry} material={materials.Wall_material} position={[-0.16, 0, 0.93]}>
        <mesh geometry={nodes.Floor014.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Bathroom_3.geometry} material={materials.Wall_material} position={[1.63, 0, 1.3]}>
        <mesh geometry={nodes.Floor019.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Bookstore_Bathroom.geometry} material={materials.Wall_material} position={[-1.3, 0, -2.08]}>
        <mesh geometry={nodes.Floor018.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Stairs.geometry} material={materials.Dark} position={[-0.28, 0, -1.48]} rotation={[Math.PI, 0, Math.PI]} scale={[0.35, 0.98, 0.54]} />
      <mesh geometry={nodes.Stairs001.geometry} material={materials.Dark} position={[-2.51, 0, -0.95]} rotation={[0, -0.04, 0]} scale={[0.35, 0.98, 0.54]} />
      <mesh geometry={nodes.Stairs002.geometry} material={materials.Dark} position={[-2.49, 0, -1.87]} rotation={[-Math.PI, 0.04, -Math.PI]} scale={[0.35, 0.98, 0.54]} />
      <mesh geometry={nodes.Stairs003.geometry} material={materials.Dark} position={[-1.9, 0, -3.92]} rotation={[0, Math.PI / 2, 0]} scale={[0.35, 0.98, 0.54]} />
      <mesh geometry={nodes.Stairs004.geometry} material={materials.Dark} position={[1, 0, -2.14]} rotation={[Math.PI, -0.79, Math.PI]} scale={[0.35, 0.98, 0.54]} />
      <mesh geometry={nodes.Stairs006.geometry} material={materials.Dark} position={[0.09, 0, 1.21]} rotation={[Math.PI, 0, Math.PI]} scale={[0.35, 0.98, 0.54]} />
      <mesh geometry={nodes.Stairs007.geometry} material={materials.Dark} position={[-0.26, 0, 2.3]} rotation={[0, 0, 0.04]} scale={[0.35, 0.98, 0.54]} />
      <mesh geometry={nodes.Stairs008.geometry} material={materials.Dark} position={[-0.02, 0, 3.3]} rotation={[0, -Math.PI / 2, 0]} scale={[0.23, 0.98, 0.51]} />
      <mesh geometry={nodes['logo-bookstore-with-crest-horizontal'].geometry} material={materials['logo-bookstore-with-crest-horizontal']} position={[-0.49, 0.03, -2.74]} scale={0.65} />
      <mesh geometry={nodes['cropped-logo-mobile'].geometry} material={materials['cropped-logo-mobile']} position={[1.81, 0.02, -1.45]} rotation={[0, Math.PI / 2, 0]} scale={0.5} />
      <mesh geometry={nodes.foodsupport.geometry} material={materials.foodsupport} position={[2.32, 0.05, 0.74]} rotation={[0, Math.PI / 2, 0]} scale={[0.5, 1, 0.5]} />
      <mesh geometry={nodes.peersupport.geometry} material={materials.peersupport} position={[-0.86, 0.05, -1.26]} scale={[0.4, 1, 0.4]} />
      <mesh geometry={nodes.starbuckslogo.geometry} material={materials.starbuckslogo} position={[1.88, 0.05, -2.58]} rotation={[0, Math.PI / 2, 0]} scale={[0.5, 1, 0.5]} />
    </group>
  )
}

useGLTF.preload('/UCCLowerLevel.gltf')
