/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 UCCLowerLevel.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/UCCLowerLevel.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Exterior_Walls.geometry} material={materials.Wall_material} position={[-3.32, 0, -5.29]}>
        <mesh geometry={nodes.Floor046.geometry} material={materials.Floor_material} position={[0, -0.02, 0]} />
      </mesh>
      <mesh geometry={nodes['Rooms_11-32'].geometry} material={materials.Wall_material} position={[-3.51, 0, -3.92]}>
        <mesh geometry={nodes.Floor.geometry} material={nodes.Floor.material} />
      </mesh>
      <mesh geometry={nodes.Bookstore_Western.geometry} material={materials.Wall_material} position={[-3, 0, -3.62]}>
        <mesh geometry={nodes.Floor001.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_73.geometry} material={materials.Wall_material} position={[-1.65, 0, -0.14]}>
        <mesh geometry={nodes.Floor021.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_79.geometry} material={materials.Wall_material} position={[-1.93, 0, -0.53]}>
        <mesh geometry={nodes.Floor023.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_78.geometry} material={materials.Wall_material} position={[-1.93, 0, -0.87]}>
        <mesh geometry={nodes.Floor022.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Peersupport_76.geometry} material={materials.Wall_material} position={[-1.93, 0, -1.54]}>
        <mesh geometry={nodes.Floor015.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Smooth_Wax_Bar_80.geometry} material={materials.Wall_material} position={[-2.86, 0, -1.56]}>
        <mesh geometry={nodes.Floor020.geometry} material={materials.Floor_material} position={[0, 0.01, 0]} />
      </mesh>
      <mesh geometry={nodes.Room_76A.geometry} material={materials.Wall_material} position={[-2.44, 0, -1.56]}>
        <mesh geometry={nodes.Floor017.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_75.geometry} material={materials.Wall_material} position={[-1.37, 0, -0.94]}>
        <mesh geometry={nodes.Floor013.geometry} material={materials.Floor_material} position={[0, 0.01, 0]} />
      </mesh>
      <mesh geometry={nodes.Western_Chiropractic_49.geometry} material={materials.Wall_material} position={[-0.84, 0, 0.33]}>
        <mesh geometry={nodes.Floor024.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Starbucks.geometry} material={materials.Wall_material} position={[0.52, 0, -3.02]}>
        <mesh geometry={nodes.Floor007.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes['Room_34B-1'].geometry} material={materials.Wall_material} position={[0.52, 0, -2.67]}>
        <mesh geometry={nodes.Floor008.geometry} material={materials.Floor_material} position={[0, 0.01, 0]} />
      </mesh>
      <mesh geometry={nodes['Room_34B-3'].geometry} material={materials.Wall_material} position={[0.53, 0, -3.4]}>
        <mesh geometry={nodes.Floor004.geometry} material={materials.Floor_material} position={[0, 0.01, 0]} />
      </mesh>
      <mesh geometry={nodes['Room_34B-2'].geometry} material={materials.Wall_material} position={[0.97, 0, -2.81]}>
        <mesh geometry={nodes.Floor006.geometry} material={materials.Floor_material} position={[0, 0.01, 0]} />
      </mesh>
      <mesh geometry={nodes['Room_34B-4'].geometry} material={materials.Wall_material} position={[0.96, 0, -3.39]}>
        <mesh geometry={nodes.Floor005.geometry} material={materials.Floor_material} position={[0, 0.01, 0]} />
      </mesh>
      <mesh geometry={nodes.Room_34A.geometry} material={materials.Wall_material} position={[0.97, 0, -3.87]}>
        <mesh geometry={nodes.Floor003.geometry} material={materials.Floor_material} position={[0, 0.01, 0]} />
      </mesh>
      <mesh geometry={nodes.Room_53.geometry} material={materials.Wall_material} position={[-0.63, 0, 1.65]}>
        <mesh geometry={nodes.Floor034.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_54B.geometry} material={materials.Wall_material} position={[0.57, 0, 1.65]}>
        <mesh geometry={nodes.Floor032.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_54A.geometry} material={materials.Wall_material} position={[-0.04, 0, 1.65]}>
        <mesh geometry={nodes.Floor033.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_57.geometry} material={materials.Wall_material} position={[-0.63, 0, 2.42]}>
        <mesh geometry={nodes.Floor043.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_66.geometry} material={materials.Wall_material} position={[-2.56, 0, 1.17]}>
        <mesh geometry={nodes.Floor037.geometry} material={materials.Floor_material} position={[0, 0.01, 0]} />
      </mesh>
      <mesh geometry={nodes.Room_61.geometry} material={materials.Wall_material} position={[-1.92, 0, 3]}>
        <mesh geometry={nodes.Floor039.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_60.geometry} material={materials.Wall_material} position={[-1.92, 0, 2.46]}>
        <mesh geometry={nodes.Floor040.geometry} material={materials.Floor_material} position={[0, 0.01, 0]} />
      </mesh>
      <mesh geometry={nodes.Room_59.geometry} material={materials.Wall_material} position={[-1.36, 0, 2.46]}>
        <mesh geometry={nodes.Floor041.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_63.geometry} material={materials.Wall_material} position={[-1.65, 0, 1.85]}>
        <mesh geometry={nodes.Floor036.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_58.geometry} material={materials.Wall_material} position={[-1.36, 0, 3]}>
        <mesh geometry={nodes.Floor038.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_65.geometry} material={materials.Wall_material} position={[-1.65, 0, 1.38]}>
        <mesh geometry={nodes.Floor045.geometry} material={materials.Floor_material} position={[0, 0.01, 0]} />
      </mesh>
      <mesh geometry={nodes.Room_67.geometry} material={materials.Wall_material} position={[-1.65, 0, 0.9]}>
        <mesh geometry={nodes.Floor044.geometry} material={materials.Floor_material} position={[0, 0.01, 0]} />
      </mesh>
      <mesh geometry={nodes.Room_41.geometry} material={materials.Wall_material} position={[0.14, 0, 0.31]}>
        <mesh geometry={nodes.Floor026.geometry} material={materials.Floor_material} position={[0, 0.01, 0]} />
      </mesh>
      <mesh geometry={nodes.Room_78C.geometry} material={materials.Wall_material} position={[-2.23, 0, -1.06]}>
        <mesh geometry={nodes.Floor016.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Multifaith_38.geometry} material={materials.Wall_material} position={[0.87, 0, -0.79]}>
        <mesh geometry={nodes.Floor029.geometry} material={materials.Floor_material} position={[0, 0.01, 0]} />
      </mesh>
      <mesh geometry={nodes.Food_Support_Services_40.geometry} material={materials.Wall_material} position={[0.87, 0, 0.98]} rotation={[0, 0, -Math.PI]} scale={-1}>
        <mesh geometry={nodes.Floor030.geometry} material={materials.Floor_material} position={[0, 0.01, 0]} />
      </mesh>
      <mesh geometry={nodes.Room_47.geometry} material={materials.Wall_material} position={[-0.44, 0, 0.33]}>
        <mesh geometry={nodes.Floor025.geometry} material={materials.Floor_material} position={[0, 0.01, 0]} />
      </mesh>
      <mesh geometry={nodes.Room_37.geometry} material={materials.Wall_material} position={[0.53, 0, 0.06]} rotation={[0, 0, -Math.PI]} scale={-1}>
        <mesh geometry={nodes.Floor028.geometry} material={materials.Floor_material} position={[0, 0.01, 0]} />
      </mesh>
      <mesh geometry={nodes.Room_56.geometry} material={materials.Wall_material} position={[0.74, 0, 2.42]}>
        <mesh geometry={nodes.Floor042.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_39.geometry} material={materials.Wall_material} position={[0.18, 0, -0.74]}>
        <mesh geometry={nodes.Floor027.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.UCC_Dental.geometry} material={materials.Wall_material} position={[0.27, 0, -1.94]}>
        <mesh geometry={nodes.Floor009.geometry} material={materials.Floor_material} position={[0, 0.01, 0]} />
      </mesh>
      <mesh geometry={nodes.Room_36A.geometry} material={materials.Wall_material} position={[-0.04, 0, -1.34]}>
        <mesh geometry={nodes.Floor010.geometry} material={materials.Floor_material} position={[0, 0.01, 0]} />
      </mesh>
      <mesh geometry={nodes.Campus_Vision_36C.geometry} material={materials.Wall_material} position={[-0.74, 0.01, -1.46]}>
        <mesh geometry={nodes.Floor012.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Pharmacy.geometry} material={materials.Wall_material} position={[-0.99, 0.05, -1.14]}>
        <mesh geometry={nodes.Floor011.geometry} material={materials.Floor_material} position={[0, 0.01, 0]} />
      </mesh>
      <mesh geometry={nodes.Bathroom_1.geometry} material={materials.Wall_material} position={[-3.14, 0, -3.63]}>
        <mesh geometry={nodes.Floor002.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Bookstore_Bathroom.geometry} material={materials.Wall_material} position={[-2.59, 0, -2.17]}>
        <mesh geometry={nodes.Floor018.geometry} material={materials.Floor_material} position={[0, 0.02, 0]} />
      </mesh>
      <mesh geometry={nodes.Bathroom_2.geometry} material={materials.Wall_material} position={[-1.26, 0, 0.9]}>
        <mesh geometry={nodes.Floor035.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Bathroom_3.geometry} material={materials.Wall_material} position={[0.56, 0, 1.16]}>
        <mesh geometry={nodes.Floor031.geometry} material={materials.Floor_material} />
      </mesh>
      <mesh geometry={nodes.Room_36B.geometry} material={materials.Wall_material} position={[-0.73, 0.01, -1.45]}>
        <mesh geometry={nodes.Floor047.geometry} material={materials.Floor_material} position={[0, 0.01, 0]} />
      </mesh>
      <mesh geometry={nodes.Stairs.geometry} material={materials.Stairs_material} position={[-1.47, 0, -1.54]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.35, 0.98, 0.54]} />
      <mesh geometry={nodes.Stairs001.geometry} material={materials['Stairs_material.001']} position={[-3.67, 0, -0.92]} scale={[0.35, 0.98, 0.54]} />
      <mesh geometry={nodes.Stairs002.geometry} material={materials['Stairs_material.002']} position={[-3.69, 0, -1.84]} rotation={[Math.PI, 0, Math.PI]} scale={[0.35, 0.98, 0.54]} />
      <mesh geometry={nodes.Stairs003.geometry} material={materials['Stairs_material.003']} position={[-2.99, 0, -4.08]} rotation={[0, Math.PI / 2, 0]} scale={[0.35, 0.98, 0.54]} />
      <mesh geometry={nodes.Stairs004.geometry} material={materials['Stairs_material.004']} position={[-0.23, 0, -2.25]} rotation={[Math.PI, -0.87, Math.PI]} scale={[0.35, 0.98, 0.54]} />
      <mesh geometry={nodes.Stairs006.geometry} material={materials['Stairs_material.006']} position={[-1.02, 0, 0.91]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.35, 0.98, 0.54]} />
      <mesh geometry={nodes.Stairs007.geometry} material={materials['Stairs_material.007']} position={[-1.4, 0, 2.28]} rotation={[0, -0.03, 0.04]} scale={[0.35, 0.98, 0.54]} />
      <mesh geometry={nodes.Stairs008.geometry} material={materials['Stairs_material.008']} position={[-1.17, 0, 3.19]} rotation={[0, -1.5, 0]} scale={[0.35, 0.98, 0.54]} />
      <mesh geometry={nodes.Stairs009.geometry} material={materials['Stairs_material.009']} position={[0.73, 0, -0.92]} rotation={[0, -Math.PI / 4, 0]} scale={[0.35, 0.98, 0.54]} />
      <mesh geometry={nodes.Floor014.geometry} material={materials.Floor_material} />
      <mesh geometry={nodes.Floor019.geometry} material={materials.Floor_material} position={[0, 0.02, 0]} />
    </group>
  )
}

useGLTF.preload('/UCCLowerLevel.gltf')
